image:
  file: .gitpod/Dockerfile

tasks:
  - name: Flutter env prep
    before: |
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    name: VNC Server
  - port: 6080
    onOpen: ignore
    name: VNC Client
    description: noVNC web client
  - port: 8080
    onOpen: ignore
    name: Flutter Web
    visibility: public

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
    - ms-azuretools.vscode-docker
