image:
  file: .gitpod/Dockerfile

tasks:
  - name: Flutter env prep
    before: |
      flutter pub get

  - name: Prebuild project for all enabled platforms
    # It should make first debugging faster
    # Since building is the step that takes longer
    init: |
      flutter build -v linux
      flutter build -v web
      flutter build -v bundle
      flutter build -v appbundle
      flutter build -v apk

ports:
  - port: 5900
    onOpen: ignore
    name: VNC Server
  - port: 6080
    onOpen: ignore
    name: VNC Client
    description: noVNC web client
  - port: 8080
    onOpen: ignore
    name: Flutter Web
    visibility: public

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
    - ms-azuretools.vscode-docker
